### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Anticept**
Per TZO's guidelines. A little reminder on what we can do to avoid another flat-splosion.

### CODE REVIEW

**Comment by Anticept** [comment]
#EnableTaggingByOrganizationMembersWhen?

**Comment by Birdtalon** [comment]
We already have a `CONTRIBUTING.md` which is altered in #1 it would probably be better to just add this as /tg/'s original `CONTRIBUTING.md` has a lot of good content.

**Comment by SamHPurp** [comment]
Yes, do it please @Birdtalon

**Comment by Birdtalon** [comment]
I've added this to my changes to `CONTRUBUTING.md` in #1

**Comment by SamHPurp** [comment]
Merged into #1

**Pull request closed without merging**
