### PR TITLE
Removes many 'memey' botany plants, seeds and references to them

### PR DESCRIPTION
**Pull request by owenowen212**
This PR starts making inroads into a revised botany system by removing many so-called 'memey' plants from botany.

A full list of plants removed is as follows:

### Removed plants/seeds:
Bluespace bananas
Mimana bananas
Rainbowweed
Lifeweed
Omegaweed
Deathweed
Combustible lemons
Snapcorn
Novaflowers
Carpet
Holymelons
Cherrybombs
Gatfruit
Walking mushrooms
Killer tomatoes
Blue tomatoes
Bluespace tomatoes

### Unremoved though questionable:
Blood tomatoes
Blumpkins
Shadowshrooms
Glowcaps
Kudzu
Moonflowers
Egg-plants
Meatwheat
Glowberries
Gold apples

**Other notes:**
- Removed mimana bread
- Changes required ingredient in melonkeg recipe from a holymelon to a regular watermelon
- Removed references to removed seeds/plants in loot crates and other maps.

### CODE REVIEW

**Comment by SamHPurp** [comment]
Does this remove the walking mushrooms entirely as a thing? Or just the ability to grow them?

**Comment by owenowen212** [comment]
Walking mushrooms should be removed entirely from the code.

**Comment by SamHPurp** [comment]
As mini annoying mobs down in a cave far past MVP, they might be viable to remain.... I'd remove any ability for these to exist outside of adminbus, but keep them in the codebase.

**Comment by owenowen212** [comment]
Scratch that, they'll still be available via adminbus:
``mob/living/simple_animal/hostile/mushroom``

**Comment by SamHPurp** [comment]
Mind testing spawning them in, and ensuring they happily run around glomping things?

**Comment by owenowen212** [comment]
0812a6f085549aea5e4cfc21fce9cc5b

**Comment by Birdtalon** [comment]
To be honest all of these things need to go, we can add our own plants further down the line with whatever effects we choose.

**Comment by FlattestGuitar** [comment]
I think we should focus on adding stuff, not ripping it out, but all of these don't really have a place in the codebase, so I think it's fine to rip 'em out.

:+1: from me.

**Pull request merged**
